/* Download woff2 (latin + vietnamese subsets) from Google Fonts css2 API
   into Visualizer/assets/fonts/ and emit styles/fonts.css with local paths. */

const fs = require("fs");
const path = require("path");

const FONT_DIR = "D:/Djstra/Visualizer/assets/fonts";
const CSS_OUT = "D:/Djstra/Visualizer/styles/fonts.css";
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36";

const FAMILIES = [
  "family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700",
  "family=Be+Vietnam+Pro:wght@400;500;600;700",
  "family=IBM+Plex+Mono:wght@400;500;600",
];
const KEEP_SUBSETS = new Set(["latin", "latin-ext", "vietnamese"]);

async function main() {
  fs.mkdirSync(FONT_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(CSS_OUT), { recursive: true });
  const url = `https://fonts.googleapis.com/css2?${FAMILIES.join("&")}&display=swap`;
  const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();

  // css2 emits "/* subset */" comment before each @font-face block
  const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face\s*\{[^}]+\})/g)];
  const seenSubsets = new Set(blocks.map((b) => b[1]));
  console.log("subsets present:", [...seenSubsets].join(", "));

  let out = "/* Generated by .shots/get-fonts.js - local Google Fonts (latin + vietnamese) */\n";
  let n = 0;
  for (const [, subset, block] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) continue;
    const fam = block.match(/font-family:\s*'([^']+)'/)[1];
    const weight = (block.match(/font-weight:\s*([\d ]+);/) || [])[1].trim().replace(/ /g, "-");
    const style = block.match(/font-style:\s*(\w+);/)[1];
    const src = block.match(/url\((https:[^)]+\.woff2)\)/)[1];
    const fname = `${fam.replace(/ /g, "")}-${weight}-${style}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(src, { headers: { "User-Agent": UA } })).arrayBuffer());
    fs.writeFileSync(path.join(FONT_DIR, fname), buf);
    out += "\n/* " + subset + " */\n" + block.replace(/url\(https:[^)]+\.woff2\)/, `url(../assets/fonts/${fname})`) + "\n";
    n++;
  }
  fs.writeFileSync(CSS_OUT, out);
  console.log(`downloaded ${n} files -> ${FONT_DIR}`);

  // report which families actually have a vietnamese subset
  for (const fam of ["Fraunces", "Be Vietnam Pro", "IBM Plex Mono"]) {
    const has = out.includes(`'${fam}'`) && new RegExp(`vietnamese \\*/\\s*@font-face\\s*\\{[^}]*'${fam}'`).test(out.replace(/\n/g, " "));
    console.log(`${fam}: vietnamese=${has}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
